version: '3.2'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=mozio
      - POSTGRES_USER=ghaff
      - POSTGRES_PASSWORD=engineer

    ports:
      - "5434:5432"


  web:
    build: .
    command: python mozio/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db