# Generated by Django 4.0.3 on 2022-03-22 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phoneNumber', models.CharField(max_length=255)),
                ('language', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=4)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
